### PR TITLE
Update to include app.js

### PR DESCRIPTION
**Pull request by tomslloyd**
Added additions features
- Included Origin as Text .
- Included Multi Pronunciations for some words.
- included Alternations in words.
- Patch phonetic to make it show multiple if present.

### CODE REVIEW

**Comment by meetDeveloper** [comment]
included Alternations in words.
What does this mean??/

**Comment by tomslloyd** [comment]
check my issues post, i'm not truly sure what the actual name for them is, but i put an image in there, then i ended up just editing yours.

**Comment by meetDeveloper** [comment]
@tomslloyd  In image which number??

**Comment by tomslloyd** [comment]
**3** you will see **noun** then under in you see **noun**, **plural noun** ....

**Comment by meetDeveloper** [comment]
Ok got it, also I have not seen any case where there is multiple pronunciation .

**Comment by tomslloyd** [comment]
yeah, it happens in some word cases, **example** search the word _insult_, it is both a _verb_ and _noun_ so it comes with two ways to say it. along with a bunch of alternations to the word for them too.

**Comment by meetDeveloper** [comment]
I think I might have to change the whole thing, because we cannot make the pronounciation just a stack of all url and not telling which belong to which, we have to see the best possible case which contain all parameter and then make model of it, I mean in verb box there would be pronunciations if verb has some, not like on top we just store all and not tell whom it belongs to.

**Comment by tomslloyd** [comment]
i see what you mean only issue is, words like aardvark only show one meaning so the Pronunciation and Phonetic word are positioned differently, currently the audio lines up with the phonetic words available, so maybe just check to see if multiple meanings are present, but the word _she_ has pronoun and noun meaning but only one way to Pronounce it.

**Comment by tomslloyd** [comment]
also update to phonetic that has them comma separated words like hello has it comma separated.

**Comment by tomslloyd** [comment]
Also there are words like _still_ that have two definitions we need to find a way to get that too.

**Comment by meetDeveloper** [comment]
Did you see something that has multiple phonetic??

**Comment by meetDeveloper** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/623ac46c-aeaa-4433-a262-223430c2e0af?env_id=ibm%3Ayp%3Aus-south "googleDictionaryAPI"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/43a8bfc9-4989-4464-8299-979f59631a9c?env_id=ibm%3Ayp%3Aus-south "googleDictionaryAPI") deployed [googleDictionaryAPI](https://github.com/meetDeveloper/googleDictionaryAPI/releases/tag/deploy-ibm-yp-eu-gb-lifeplusplus-API-s-20180731-041607 "deploy-ibm-yp-eu-gb-lifeplusplus-API-s-20180731-041607") to [API's](https://console.bluemix.net/apps/0971aef0-04d8-454a-b263-f77d06d21309?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:lifeplusplus:API's"), including commit 1dc6365d1b68daacec98100cdd0128b04cf25947

**Comment by meetDeveloper** [comment]
Search for set now, I think there was some mistake in your code.

**Pull request merged**
