### PR TITLE
creating main definition

### PR DESCRIPTION
**Pull request by roaugusto**
Some words didn't return a definition like the words "is" or "are".
So, I did some adjustments to return something in this case.

I don't know whether this update was the best way, so feel free to add or change anything.

### CODE REVIEW

**Comment by meetDeveloper** [comment]
@roaugusto The words did not return any result because they cross referred another word. Like _are_ referred to be, and so does _is_. So that is why they were not coming, I am going to integrate it. Thanks for letting me know.

**Comment by roaugusto** [comment]
Hey,

By the way, It's an awesome API.
And sorry if I did some mess... This is my first contact trying to
collaborate with a project on GitHub and I don't know if I did in the
correct way. And like I said, I don't know if this solution was the best
solution. Feel free to change in the best way.

Regards,

Rodrigo






Em seg, 3 de dez de 2018 às 15:38, meetDeveloper <notifications@github.com>
escreveu:

**Comment by meetDeveloper** [comment]
@roaugusto You did not made any mess, and did very good job at correcting it, I am checking some edge cases and there is one thing, one should always try to find generality and make general solution for all cases, it is a good practice according to me, so I am trying to find general case, so that I do not have to have and if and else thing. 

Thanks, it is because of people like you, that I get motivation to further improve this API. I never thought it would be used this much. Thanks a lot :) It matters a lot.

This was my first github project and it feels good when many people uses it.

**Comment by roaugusto** [comment]
Hey @meetDeveloper ,

I was doing some more tests and I realized that the word "tacky" isn't returning all the definitions. So, I did some more changes, but this time it a bit more complex. Take a look and if you want, feel free to implement in your API.

I think now is return more results. But I didn't too many tests yet.

**Comment by meetDeveloper** [comment]
@roaugusto I have implemented the changes which cover everything from returning all definitions and also returning meaning for words like 'is' and 'are', Kindly see and tell me does that work for you.

**Pull request closed without merging**
